### ISSUE TITLE
prepare release v1.2

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#251]
The following issue captures the overall intent to release v1.2 of the `sphinxcontrib-confluencebuilder` module. This includes issues and more found under [1.2 milestone](https://github.com/sphinx-contrib/sphinxcontrib-confluencebuilder/milestone/5).

### initial comments
There have been a bunch of changes introduced over this year and it may be a good time to wrap everything into a new stable release. We can still complete many issues captured in [1.2 milestone](https://github.com/sphinx-contrib/sphinxcontrib-confluencebuilder/milestone/5). There will be some extensive testing to ensure this extension works with all active variants of Confluence. Ideally, it may be possible to finalize the release by the end of this calendar year.

This issue will be updated to reflect progress as the release is made. Feel free to comment if desired.

# phase 01 -- "final implementation run"

- [x] For [1.2 milestone](https://github.com/sphinx-contrib/sphinxcontrib-confluencebuilder/milestone/5), ensure all pull requests have been reviewed/merged and issues ready for closure (marked as "pending next release").

# phase 02 -- "system testing"

With appropriate changes merged in, validation tests will need to be performed under the following environments:

- [x] Confluence Cloud (Organization Space)
- [x] Confluence Cloud (User Space)
- [x] Confluence Server
    - [x] Confluence Server v6.7
    - [x] Confluence Server v6.8
    - [x] Confluence Server v6.9
    - [x] Confluence Server v6.10
    - [x] Confluence Server v6.11
    - [x] Confluence Server v6.12
    - [x] Confluence Server v6.13
    - [x] Confluence Server v6.14
    - [x] Confluence Server v6.15
    - [x] Confluence Server v7.0
    - [x] Confluence Server v7.1
    - [x] Confluence Server v7.2

# phase 03 -- "release"

- [x] Update `CHANGES.rst`, replacing master with release version and date.
- [x] Ensure version values in the implementation and incremented and tagged appropriately.
- [x] Push release cycle commits and tag to `origin/master.`
- [x] From release tag, build and publish to PyPI (using twine). Ensure twine is invoked with the `--universal` option to ensure packaging properly reflects `py2.py3` support.

# phase 04 -- "sanity checks and cleanup"
- [x] Verify Read the Docs space reflects the most recent documentation.
- [x] Un-tag any issues with "pending next release" and close the issues in [1.2 milestone](https://github.com/sphinx-contrib/sphinxcontrib-confluencebuilder/milestone/5).
- [x] Update online validation set demonstration site to include the v1.2 release.
- [x] Close this issue.

**Comment by jdknight** [comment]
fyi | @tonybaloney

**Comment by jdknight** [comment]
For those interested, the goal is to wrap-up changes for this milestone during the weekend of December 28-29th 2019 (not fixed). Ideally, all phases will be complete within the first half of January 2020.

**Comment by jdknight** [comment]
This extension's v1.2 release is now available on PyPI. Users can consult [CHANGES.rst](https://github.com/sphinx-contrib/confluencebuilder/blob/master/CHANGES.rst) for the most recent changes introduced in the release. Thanks to all the new [contributors](https://github.com/sphinx-contrib/confluencebuilder/blob/master/AUTHORS) this release and everyone reporting issues to help improve this extension.

And Happy New Year. :tada:
